name: Export Genesis Archive

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export-shell:
    runs-on: ubuntu-latest
    env:
      GH_PAT:      ${{ secrets.GH_TOKEN }}
      REPO_BRANCH: main

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Archive repository contents
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y zip
          zip -r genesis-archive.zip . \
            -x ".git/*" "genesis-archive.zip"

      - name: Commit & push genesis-archive.zip
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add genesis-archive.zip
          if ! git diff --cached --quiet; then
            git commit -m "ci: update Genesis Archive Shell"
            git push origin $REPO_BRANCH
          else
            echo "No changes to genesis-archive.zip"
          fi

      - name: Create or update Release asset
        uses: ncipollo/release-action@v1
        with:
          tag: genesis-latest
          artifact: genesis-archive.zip
          allowUpdates: true
          removeArtifacts: true
          skipIfReleaseExists: false

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": ":white_check_mark: *Export Genesis Archive* `${{ job.status }}`\n• <${{ github.run_url }}|Details>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
