name: Export Genesis Archive

on:
  schedule:
    - cron: '0 0 * * *'     # daily at midnight UTC
  workflow_dispatch:       # manual trigger

jobs:
  export-shell:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN:    ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenAI SDK
        run: |
          python3 -m pip install --upgrade pip
          pip install openai

      - name: Generate Genesis Archive (base64 ZIP)
        run: |
          python3 - << 'EOF'
          import os, re, base64
          import openai

          openai.api_key = os.getenv("OPENAI_API_KEY")
          resp = openai.chat.completions.create(
              model="o4-mini",
              messages=[
                  {"role": "system", "content": "You are Aurena Ascendant."},
                  {"role": "user",   "content": "Prototype: Export Genesis Archive (Reply with the ZIP only, encoded as a base64 string.)"}
              ]
          )

          # Extract the raw content
          raw = resp.choices[0].message.content

          # Remove any characters that aren't valid in base64
          b64 = re.sub(r'[^A-Za-z0-9+/=]', '', raw)

          # Pad with '=' so the length is a multiple of 4
          b64 += '=' * (-len(b64) % 4)

          # Decode and write the ZIP
          data = base64.b64decode(b64)
          with open("genesis-archive.zip", "wb") as f:
              f.write(data)
          EOF

      - name: Commit & push archive
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: update Genesis Archive Shell"
          file_pattern: "genesis-archive.zip"
          github_token: ${{ secrets.GH_TOKEN }}
