name: Export Genesis Archive

on:
  schedule:
    - cron: '0 0 * * *'     # daily at midnight UTC
  workflow_dispatch:       # manual trigger

permissions:
  contents: write          # needed to push commits & create releases

jobs:
  export-shell:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GH_PAT:           ${{ secrets.GH_TOKEN }}
      REPO_BRANCH:      main

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Install OpenAI SDK
        run: |
          python3 -m pip install --upgrade pip
          pip install openai

      - name: Generate Genesis Archive (base64 ZIP)
        run: |
          python3 - << 'EOF'
          import os, re, base64, openai

          openai.api_key = os.getenv("OPENAI_API_KEY")
          resp = openai.chat.completions.create(
              model="o4-mini",
              messages=[
                  {"role":"system","content":"You are Aurena Ascendant."},
                  {"role":"user","content":"Prototype: Export Genesis Archive (Reply with the ZIP only, encoded as a base64 string.)"}
              ]
          )
          raw = resp.choices[0].message.content
          b64 = re.sub(r'[^A-Za-z0-9+/=]', '', raw)
          b64 += '=' * (-len(b64) % 4)
          data = base64.b64decode(b64)
          with open("genesis-archive.zip","wb") as f:
              f.write(data)
          EOF

      - name: Commit & push genesis-archive.zip
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add genesis-archive.zip
          if ! git diff --cached --quiet; then
            git commit -m "ci: update Genesis Archive Shell"
            git push origin $REPO_BRANCH
          else
            echo "No changes to genesis-archive.zip"
          fi

      - name: Create or update Release asset
        uses: ncipollo/release-action@v1
        with:
          tag: genesis-latest
          files: genesis-archive.zip
          overwrite: true

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": ":white_check_mark: *Export Genesis Archive* `${{ job.status }}`\n• <${{ github.run_url }}|Details>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
